spring.application.name: bookshop-demo
server:
  port: 8080

spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:bookshop_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true


